#!/usr/bin/env python3
"""Export the built-in demo models as Wavefront OBJ files for the MCU runtime.

The resulting files follow a very small subset of the OBJ format:

* vertex lines are emitted as `v x y z r g b` where the colours are 0-255
* face lines are triangles (`f i j k`) with 1-based indices

Usage:
    python tools/export_models.py --out build/models

Copy the generated *.obj files to the SD card under e.g. 0:/models/.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import textwrap


class Model:
    def __init__(self, name: str, vertices, triangles):
        self.name = name
        self.vertices = vertices
        self.triangles = triangles

    def write(self, out_dir: Path) -> Path:
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{self.name}.obj"
        with path.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(textwrap.dedent(f"""
                # Auto-generated by tools/export_models.py
                # model: {self.name}
            """).lstrip())
            for vx in self.vertices:
                x, y, z, r, g, b = vx
                fh.write(f"v {x:.6f} {y:.6f} {z:.6f} {int(r)} {int(g)} {int(b)}\n")
            for tri in self.triangles:
                a, b, c = (index + 1 for index in tri)
                fh.write(f"f {a} {b} {c}\n")
        return path


MODELS = [
    Model(
        "cube",
        [
            (-0.5, -0.5, -0.5, 15, 0, 15),
            (0.5, -0.5, -0.5, 15, 15, 0),
            (0.5, 0.5, -0.5, 0, 15, 15),
            (-0.5, 0.5, -0.5, 15, 0, 15),
            (-0.5, -0.5, 0.5, 15, 15, 0),
            (0.5, -0.5, 0.5, 0, 15, 15),
            (0.5, 0.5, 0.5, 15, 0, 15),
            (-0.5, 0.5, 0.5, 15, 15, 0),
        ],
        [
            (4, 5, 6), (4, 6, 7),
            (1, 0, 3), (1, 3, 2),
            (3, 7, 6), (3, 6, 2),
            (0, 1, 5), (0, 5, 4),
            (1, 2, 6), (1, 6, 5),
            (0, 7, 3), (0, 4, 7),
        ],
    ),
    Model(
        "pyramid",
        [
            (-0.5, -0.5, -0.5, 0, 0, 0),
            (0.5, -0.5, -0.5, 15, 0, 0),
            (0.5, -0.5, 0.5, 15, 15, 0),
            (-0.5, -0.5, 0.5, 0, 15, 0),
            (0.0, 0.5, 0.0, 15, 15, 15),
        ],
        [
            (1, 0, 4), (2, 1, 4), (3, 2, 4), (0, 3, 4),
            (0, 1, 2), (0, 2, 3),
        ],
    ),
    Model(
        "plane",
        [
            (-4.0, 0.0, -4.0, 8, 8, 8),
            (4.0, 0.0, -4.0, 8, 8, 8),
            (4.0, 0.0, 4.0, 8, 8, 8),
            (-4.0, 0.0, 4.0, 8, 8, 8),
        ],
        [
            (0, 1, 2), (0, 2, 3),
        ],
    ),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True, help="Directory to write model files")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    produced = []
    for model in MODELS:
        produced.append(model.write(args.out))
    print(f"Wrote {len(produced)} model(s) to {args.out}")


if __name__ == "__main__":
    main()
